\c colors_dev;

INSERT INTO songs (name, artist, album, year, genre,is_favorite) VALUES
('A Simple Design (Original Mix)','The Juan Maclean','A Simple Design',2015,'Indie Dance  Nu Disco',false),
('A Simple Design (Purple Disco Machine Remix)','The Juan Maclean','A Simple Design',2015,'Deep House',false),
('A Simple Design (Purple Disco Machine Remix) (Purple Disco Machine Remix)','The Juan Maclean','Hed Kandi 2016',2015,'Deep House',false),
('A Stone Rollin (Sergio Pardo Remix)','Yakka','Pool Party Punta del Este 2015',2015,'House',false),
('A Thousand Dances (Remixed) (Spiritchaser Spacefunk Dub Extended Mix)','Terry Grant Spiritchaser','A Thousand Dances (Remixed)',2020,'House',false),
('Aaaih (Original Mix)','Soul Speech','Feelin EP',2018,'House',false),
('ABC Dream (Original Mix)','Uabos','Dusk',2015,'House',false),
('Aber (Original Mix)','Tobtok','Poolside Ibiza 2016',2016,'House',false),
('Abomination (Original Mix)','Sundre','Abomination',2015,'Deep House',false),
('About A Young Lady (Eric Volta Dub Mix)','Stefano Ritteri','About A Young Lady EP',2015,'Tech House',false),
('About House Music (Original Mix)','Thomas Brown','About House Music',2016,'House',false),
('About You (Original Mix)','Tim Toh, youANDme','About You  Listen To',2016,'Tech House',false),
('Above The Sky (Erro & Sameina Remix)','Venger Collective','Above The Sky',2015,'House',false),
('Abrete Corazon (Koko (Italy) Remix)','TwentyNine','Abrete Corazon EP',2014,'Tech House',false),
('Abyss (Original Mix)','Stulp Fiction, Kai Peh','Abyss  Taar',2017,'House',false),
('ACDC (Guy J Remix)','X-Press 2','ACDC (Guy J Remix)  Future (Guy J Remix)',2021,'Melodic House & Techno',false),
('Acamon (Original Mix)','Tato','Acamon EP',2014,'Tech House',false),
('Accept Me Junior Vasquez Mix','Vernessa Mitchell','',2005,'House',false),
('Access Denied (Funky Truckerz Remix)','Sosua & Mad','Access Denied',2013,'House',false),
('Accidental (Original Mix)','Tony Lenz','Accidental Ep',2013,'Tech House',false),
('Move Out (Original Mix)', 'Sharam Jey', 'null',2023,'House',true),
('Boogie (Original Mix)', 'Rubber People', 'null',2023,'House', true),
('Find A Way (Extended Mix)', 'OFFAIAH', 'null',2023,'House', true),
('My Paradise (Damian Lazarus Extended Re-Shape)', 'Jamie Jones', 'null',2023,'House', true),
('Fever (Extended Mix)', 'David Penn, KPD', 'null',2023,'House', true);